// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXTWnAOYT5npsgVI5pTQSemhvMkHI0arQ',
    appId: '1:1056152050367:web:619de44aa1a986154e840a',
    messagingSenderId: '1056152050367',
    projectId: 'farmtrack-ebd3b',
    authDomain: 'farmtrack-ebd3b.firebaseapp.com',
    storageBucket: 'farmtrack-ebd3b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVxVO_WnV5yaXojpG2_ltny_1ICbk2IFY',
    appId: '1:1056152050367:android:f252d21de7f8e5574e840a',
    messagingSenderId: '1056152050367',
    projectId: 'farmtrack-ebd3b',
    storageBucket: 'farmtrack-ebd3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg8P3gzXiRhCnW7jGKYax-Qb005berprY',
    appId: '1:1056152050367:ios:274bbae5cdd0a98f4e840a',
    messagingSenderId: '1056152050367',
    projectId: 'farmtrack-ebd3b',
    storageBucket: 'farmtrack-ebd3b.firebasestorage.app',
    iosBundleId: 'com.example.farmtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg8P3gzXiRhCnW7jGKYax-Qb005berprY',
    appId: '1:1056152050367:ios:274bbae5cdd0a98f4e840a',
    messagingSenderId: '1056152050367',
    projectId: 'farmtrack-ebd3b',
    storageBucket: 'farmtrack-ebd3b.firebasestorage.app',
    iosBundleId: 'com.example.farmtrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXTWnAOYT5npsgVI5pTQSemhvMkHI0arQ',
    appId: '1:1056152050367:web:3b3e263a952fa8f54e840a',
    messagingSenderId: '1056152050367',
    projectId: 'farmtrack-ebd3b',
    authDomain: 'farmtrack-ebd3b.firebaseapp.com',
    storageBucket: 'farmtrack-ebd3b.firebasestorage.app',
  );

}